name: Create a Release on Push

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - dist/**

jobs:
  checkout-zip-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            dist
          # We intended to fetch tags, but it seems the simple
          # `fetch-tags: true` doesn't work. The
          # https://github.com/actions/checkout/issues/1471 thread described the
          # discussion and suggested the following way that may balance between
          # a deep fetch and speed.
          fetch-depth: 0
          filter: tree:0
      - name: Get latest tag
        run: |
          TAG="$( git describe --tags `git rev-list --tags --max-count=1` )"
          echo "Latest tag: $TAG"
          NEW_TAG="$( echo "$TAG" | awk -v 'FS=.' '{print $1 "." $2 "." $3 + 1}' )"
          echo "New tag: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
      - name: Zip
        run: |
          cd dist
          DATE="$( TZ=America/Los_Angeles date '+%Y-%m-%d' )"
          echo "Will do sed -e s/%VERSION%/${{ env.NEW_TAG }}/ -e s/%DATE%/$DATE/"
          sed -e 's/%VERSION%/${{ env.NEW_TAG }}/' -e "s/%DATE%/$DATE/" -i Fusion/*.setting
          zip -1 -v PerspectiveZoom.drfx -r Edit/ Fusion/
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/PerspectiveZoom.drfx
          tag_name: ${{ env.NEW_TAG }}
          name: Release ${{ env.NEW_TAG }}
