name: Create a Release on Push

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - dist/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # We intended to fetch tags, but it seems the simple
          # `fetch-tags: true` doesn't work. The
          # https://github.com/actions/checkout/issues/1471 thread described the
          # discussion and suggested the following way that may balance between
          # a deep fetch and speed.
          fetch-depth: 0
          filter: tree:0
      - name: Get latest tag
        id: get_latest_tag
        run: |
          TAG=$( git describe --tags `git rev-list --tags --max-count=1` )
          echo "Latest tag: $TAG"
          TAG2=$( echo "$TAG" | awk -v 'FS=.' '{print $1 "." $2 "." $3 + 1}' )
          echo "New tag: $TAG2"
          echo "new_tag=$TAG2" >> $GITHUB_ENV
      - name: Build
        run: cd dist && zip -1 -v PerspectiveZoom.drfx -r Edit/ Fusion/
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/PerspectiveZoom.drfx
          tag_name: ${{ env.new_tag }}
          name: Release ${{ env.new_tag }}
