name: Create a Release on Push

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - dist/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Get latest tag
        id: get_latest_tag
        run: |
          TAG=$( git describe --tags `git rev-list --tags --max-count=1` )
          echo "Latest tag: $TAG"
          TAG2=$( echo "$TAG" | awk -v 'FS=.' '{print $1 "." $2 "." $3 + 1}' )
          echo "New tag: $TAG2"
          echo "::set-output name=new_tag::$TAG2"
      - name: Build
        run: cd dist && zip -1 -v PerspectiveZoom.drfx -r Edit/ Fusion/
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/PerspectiveZoom.drfx
          tag_name: ${{ steps.get_version.outputs.new_tag }}
          name: Release ${{ steps.get_version.outputs.new_tag }}
